name: ARM64 Build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:

env:
  RUST_TEST_THREADS: 4
  # TODO: remove this or increase this when contract size limit is not a problem
  SOLC_OPTIMIZER_RUNS: 20

jobs:
  build:
    runs-on: [self-hosted, arm64]
    container:
      image: ghcr.io/espressosystems/nix:main
      volumes:
        - github_nix_251:/nix
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        name: Cancel Outdated Builds
        with:
          access_token: ${{ github.token }}

      - uses: cachix/cachix-action@v10
        with:
          name: espresso-systems-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Potential broken submodules fix
        run: |
          git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :

      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Work around git issue after git CVE-2022-24765 fix.
        run: git config --global --add safe.directory "$PWD"

      - name: Initialize Nix Shell
        run: nix-shell --run "echo Init"

      - name: Why does this work
        run: nix-shell --run "pnpm --recursive install"

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            target
          # todo: add nix key, for example:  nix-instantiate shell.nix | sha256sum  | head -c 10
          key: arm-cape-v5-${{ hashFiles('Cargo.lock') }}

      - name: Build all executables
        run: nix-shell --run "cargo build --release"

      - uses: actions/upload-artifact@v2
        with:
          name: wallet-webserver-arm64
          path: |
            target/release/wallet-api

      - uses: actions/upload-artifact@v2
        with:
          name: services-executables-arm64
          path: |
            target/release/address-book
            target/release/eqs
            target/release/faucet
            target/release/minimal-relayer

  docker-wallet:
    runs-on: [self-hosted, arm64]
    needs: build
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          path: wallet-checkout

      - uses: actions/download-artifact@v2
        with:
          name: wallet-webserver-arm64
          path: wallet-checkout/target/release/

      - name: Set linker/loader to not be nix
        run: patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 ./wallet-checkout/target/release/wallet-api

      - uses: docker/setup-buildx-action@v1
        name: Setup Docker BuildKit (buildx)
        with:
          driver: docker

      - uses: docker/login-action@v1
        name: Login to Github Container Repo
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        name: Generate Docker Metadata
        id: meta
        with:
          images: ghcr.io/espressosystems/cape/wallet

      - uses: docker/build-push-action@v2
        name: Build and Push Docker
        with:
          context: ./wallet-checkout/
          file: ./wallet-checkout/wallet.Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-services:
    runs-on: [self-hosted, arm64]
    needs: build
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          path: services-checkout

      - uses: actions/download-artifact@v2
        with:
          name: services-executables-arm64
          path: services-checkout/target/release/

      - uses: docker/setup-buildx-action@v1
        name: Setup Docker BuildKit (buildx)
        with:
          driver: docker

      - uses: docker/login-action@v1
        name: Login to Github Container Repo
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        name: Generate Docker Metadata
        id: meta
        with:
          images: ghcr.io/espressosystems/cape/services

      - name: Generate base image
        run: cd services-checkout && bin/build-docker-base

      - uses: docker/build-push-action@v2
        name: Build and Push Docker
        with:
          context: ./services-checkout/
          file: ./services-checkout/services.Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
